<a href="https://colab.research.google.com/github/headnotf0und/refactored-octo-rotary-phone/blob/main/Chromebooki_rev_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pymcdm

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.1/106.1 kB 1.3 MB/s eta 0:00:00


In [2]:
import pymcdm as pm
import numpy as np

In [3]:
# Dane o Chromebookach w formie listy list bez kolumny z nazwą modelu
chromebooks = np.array([
    [325, 11, 32, 4, 2436, 2], # Acer Spin 511
    [259, 11, 32, 4, 1178, 0], # Acer R11
    [339, 11, 32, 4, 1423, 0], # ASUS Chromebook C214M
    [300, 14, 64, 8, 2867, 5], # ASUS CHROMEBOOK C433T
    [309, 14, 64, 8, 1107, 3]  # Asus Chromebook C523N
])

# Wyświetlenie danych
for chromebook in chromebooks:
    print(chromebook)



[ 325   11   32    4 2436    2]
[ 259   11   32    4 1178    0]
[ 339   11   32    4 1423    0]
[ 300   14   64    8 2867    5]
[ 309   14   64    8 1107    3]


In [4]:
# Zdefiniuj wagi dla każdego kryterium
weights = np.ones(6) / 6
# Zdefiniuj zysk / strata dla każdego kryterium
types = np.array([-1, -1, 1, 1, 1, 1,])
# 1 jako zysk (max), -1 jako koszt (min)

In [5]:
topsis = pm.methods.TOPSIS()

pref = topsis(chromebooks, weights, types)

rank = topsis.rank(pref)
# W przypadku metody TOPSIS najbardziej znacząca wartość preferencji (bliższa do 1) oznacza lepszą alternatywę.
print(np.round(pref, 4))
print('Alternatywy od najlepszej:', rank)


[0.4297 0.4167 0.3197 0.6469 0.4975]
Alternatywy od najlepszej: [3. 4. 5. 1. 2.]
